/* Auto-generated by Heritage /community/publish at 2026-06-15T16:49:26Z
 * Edit via Heritage › Community control panel, not directly.
 */
window.SITE = {
  "group": {
    "name": "Colombia OpenInfra User Group",
    "nameShort": "Colombia OpenInfra",
    "description": {
      "es": "Comunidad abierta para la colaboración y exploración de infraestructura abierta en Colombia.",
      "en": "Open community for the collaboration and exploration of open infrastructure in Colombia."
    },
    "founded": "2022",
    "members": 376,
    "city": "Bogotá",
    "country": "Colombia",
    "countryCode": "CO",
    "events": 7
  },
  "socials": {
    "meetup": "https://www.meetup.com/colombia-openinfra-user-group/",
    "youtube": "https://www.youtube.com/@colombiaopeninfrausergroup",
    "linkedin": "https://www.linkedin.com/company/colombia-openinfra-user-group",
    "instagram": "https://www.instagram.com/colombiaopeninfrausergroup/",
    "github": "https://github.com/lfarizav/colombia-openinfra-user-group"
  },
  "registrationUrl": "https://www.meetup.com/colombia-openinfra-user-group/",
  "chatUrl": "https://www.meetup.com/colombia-openinfra-user-group/",
  "sponsors": [
    {
      "name": "Pontificia Universidad Javeriana",
      "url": "https://www.javeriana.edu.co",
      "role": {
        "es": "Sede y Patrocinador Principal",
        "en": "Venue & Principal Sponsor"
      }
    },
    {
      "name": "OpenInfra Foundation",
      "url": "https://openinfra.dev",
      "role": {
        "es": "Fundación Organizadora",
        "en": "Organizing Foundation"
      }
    }
  ],
  "events": [
    {
      "id": "evt-5",
      "number": 5,
      "title": {
        "en": "Fifth Colombia OpenInfra User Group Event",
        "es": "Quinto Evento Colombia OpenInfra User Group"
      },
      "date": "2026-06-05",
      "venue": "Pontificia Universidad Javeriana, Bogotá",
      "attendees": 62,
      "upcoming": false,
      "description": {
        "en": "Convergence of telecoms, Kubernetes, AI, observability, Open Source, regulation, and academia. Sessions on AI in telco, cellular network automation, eBPF observability, AI regulation, and Kubernetes in academia.",
        "es": "Convergencia entre telecomunicaciones, Kubernetes, Inteligencia Artificial, observabilidad, Open Source, regulación y academia. Sesiones sobre IA en telco, automatización de redes celulares, observabilidad con eBPF, regulación de IA y Kubernetes en la academia."
      },
      "meetupUrl": "https://www.meetup.com/colombia-openinfra-user-group/events/313396409/",
      "imageUrl": "assets/Cover Website - 5.svg",
      "speakers": [
        {
          "name": "Mariela Curiel",
          "affiliation": "Pontificia Universidad Javeriana – Profesora Ingeniería de Sistemas",
          "talk": {
            "en": "Kubernetes Seeds at Universidad Javeriana",
            "es": "Semillas de Kubernetes en la Universidad Javeriana"
          },
          "slidesUrl": null
        },
        {
          "name": "Luis Felipe Ariza Vesga",
          "affiliation": "Beanters – Kubestronaut y Organizador Colombia OpenInfra",
          "talk": {
            "en": "LTE and 5G cellular network automation using natural language and AI",
            "es": "Automatización de redes celulares LTE y 5G con lenguaje natural e IA"
          },
          "slidesUrl": null
        },
        {
          "name": "Daniel Gerardo Escamilla Montoya",
          "affiliation": "NTT DATA – Lead Engineer",
          "talk": {
            "en": "Open Source as an innovation platform for telecoms",
            "es": "Open Source como plataforma de innovación para telecomunicaciones"
          },
          "slidesUrl": null
        },
        {
          "name": "Fabian Humberto Herrera Santana",
          "affiliation": "Viceministerio de Conectividad – Asesor",
          "talk": {
            "en": "AI regulation applied to critical infrastructure and telecoms",
            "es": "Regulación de IA aplicada a infraestructuras críticas y telecomunicaciones"
          },
          "slidesUrl": null
        },
        {
          "name": "Nicolas Bayona",
          "affiliation": "Endava – Kubestronaut y DevOps Engineer",
          "talk": {
            "en": "Kubernetes incident resolution using AI agents",
            "es": "Resolución de incidentes en Kubernetes con agentes de IA"
          },
          "slidesUrl": null
        },
        {
          "name": "Jhonnatan Gil Chaves",
          "affiliation": "Globant – DevOps/SRE Engineer",
          "talk": {
            "en": "High-performance eBPF observability for cloud-native and telecom environments",
            "es": "Observabilidad de alto rendimiento con eBPF para entornos cloud-native y telecom"
          },
          "slidesUrl": null
        },
        {
          "name": "Gabriel Andrés Alzate Acuña",
          "affiliation": "DatosCol – CEO",
          "talk": {
            "en": "Infrastructure cost optimisation with AI, automation and open source",
            "es": "Optimización de costos de infraestructura con IA, automatización y software abierto"
          },
          "slidesUrl": null
        }
      ]
    },
    {
      "id": "evt-4",
      "number": 4,
      "title": {
        "en": "KCD 2025 — Colombia OpenInfra User Group & OSPO-TODO Colocated Event",
        "es": "KCD 2025 — Colombia OpenInfra User Group & OSPO-TODO Colocated Event"
      },
      "date": "2025-08-29",
      "venue": "Pontificia Universidad Javeriana, Bogotá",
      "attendees": 18,
      "upcoming": false,
      "description": {
        "en": "For the first time in Colombia, KCD 2025, OSPO-TODO, and the Colombia OpenInfra User Group came together in a single event. Sessions on cloud-native infrastructure, Kubernetes in telco, and 4G/5G networks in academia.",
        "es": "Por primera vez en Colombia, KCD 2025, OSPO-TODO y el Colombia OpenInfra User Group se unen en un solo evento. Sesiones sobre infraestructura cloud-native, Kubernetes en telco, redes 4G/5G en la academia."
      },
      "meetupUrl": "https://www.meetup.com/colombia-openinfra-user-group/events/307096751/",
      "imageUrl": "assets/Cover Website - 4.svg",
      "speakers": [
        {
          "name": "Danilo Granados",
          "affiliation": "KubeAstronaut",
          "talk": {
            "en": "Deploying Telco functions on Kubernetes with Multus CNI",
            "es": "Desplegando funciones Telco en Kubernetes con Multus CNI"
          },
          "slidesUrl": null
        },
        {
          "name": "Luis Felipe Ariza Vesga",
          "affiliation": "Organizador Colombia OpenInfra User Group",
          "talk": {
            "en": "Enhancing Stability and Enabling Cloud-Native Capabilities for Private Cellular Networks",
            "es": "Mejorando la estabilidad y habilitando capacidades cloud-native para redes celulares privadas"
          },
          "slidesUrl": null
        },
        {
          "name": "Sergio Lopez",
          "affiliation": "Pontificia Universidad Javeriana",
          "talk": {
            "en": "4G and 5G Network Deployment in Academia",
            "es": "Despliegue de Redes 4G y 5G en la academia"
          },
          "slidesUrl": null
        },
        {
          "name": "Juan Sebastian Clavijo",
          "affiliation": "Pontificia Universidad Javeriana",
          "talk": {
            "en": "4G and 5G Network Deployment in Academia",
            "es": "Despliegue de Redes 4G y 5G en la academia"
          },
          "slidesUrl": null
        }
      ]
    },
    {
      "id": "evt-87",
      "number": null,
      "title": {
        "en": "OpenStack 15th Birthday — OpenInfra Colombia & Cloud Native Bogotá",
        "es": "Celebración 15 años de OpenStack — OpenInfra Colombia & Cloud Native Bogotá"
      },
      "date": "2025-07-03",
      "venue": "Pontificia Universidad Javeriana, Bogotá",
      "attendees": 12,
      "upcoming": false,
      "description": {
        "en": "Special event co-organised by OpenInfra Colombia and Cloud Native Bogotá to celebrate OpenStack's 15th anniversary. Sessions on cloud-native evolution, the OpenInfra-Linux Foundation merger, and networking.",
        "es": "Evento especial co-organizado por OpenInfra Colombia y Cloud Native Bogotá para celebrar el 15° aniversario de OpenStack. Sesiones sobre evolución de la nube nativa, la fusión OpenInfra-Linux Foundation y networking."
      },
      "meetupUrl": "https://www.meetup.com/colombia-openinfra-user-group/events/308383244/",
      "imageUrl": "https://secure.meetupstatic.com/photos/event/5/7/0/a/highres_528442282.jpeg",
      "speakers": [
        {
          "name": "Iván Camargo",
          "affiliation": "Google",
          "talk": {
            "en": "Cloud-native technologies: field experiences",
            "es": "Tecnologías nativas en la nube: experiencias de campo"
          },
          "slidesUrl": null
        },
        {
          "name": "Nicolas Bayona",
          "affiliation": "Endava – Kubestronaut",
          "talk": {
            "en": "Cloud-native technical talk",
            "es": "Charla técnica cloud-native"
          },
          "slidesUrl": null
        },
        {
          "name": "Luis Felipe Ariza Vesga",
          "affiliation": "Colombia OpenInfra",
          "talk": {
            "en": "OpenStack evolution and its impact on open infrastructure",
            "es": "Evolución de OpenStack y su impacto en la infraestructura abierta"
          },
          "slidesUrl": null
        }
      ]
    },
    {
      "id": "evt-3",
      "number": 3,
      "title": {
        "en": "Third Colombia OpenInfra User Group Event",
        "es": "Tercer Evento Colombia OpenInfra User Group"
      },
      "date": "2024-03-19",
      "venue": "Pontificia Universidad Javeriana, Bogotá",
      "attendees": 76,
      "upcoming": false,
      "description": {
        "en": "Third OpenInfra community gathering in Colombia. Hybrid event with sessions on cloud-native infrastructure, bare-metal Kubernetes, NFV virtualisation, and open-source mobile networks for academia.",
        "es": "Tercer encuentro de la comunidad OpenInfra en Colombia. Evento híbrido con sesiones sobre infraestructura cloud-native, Kubernetes en baremetal, virtualización de funciones de red NFV y redes móviles open-source para la academia."
      },
      "meetupUrl": "https://www.meetup.com/colombia-openinfra-user-group/events/297052726/",
      "imageUrl": "https://secure.meetupstatic.com/photos/event/6/d/2/4/highres_519747940.jpeg",
      "speakers": [
        {
          "name": "Daniel Jaramillo",
          "affiliation": "Pontificia Universidad Javeriana",
          "talk": {
            "en": "Event introduction",
            "es": "Introducción al evento"
          },
          "slidesUrl": null
        },
        {
          "name": "Luis Felipe Ariza Vesga",
          "affiliation": "Organizador Colombia OpenInfra User Group",
          "talk": {
            "en": "Motivational talk and cellular network demonstration",
            "es": "Presentación motivacional y demostración de redes celulares"
          },
          "slidesUrl": null
        },
        {
          "name": "Javier Andrés Marroquín Barreto",
          "affiliation": "Pontificia Universidad Javeriana",
          "talk": {
            "en": "OpenStack as an enabler for Network Function Virtualisation (NFV)",
            "es": "OpenStack como habilitador de la Virtualización de Funciones de Red (NFV)"
          },
          "slidesUrl": null
        },
        {
          "name": "Ivan Camargo",
          "affiliation": "Google",
          "talk": {
            "en": "Cloud Native Architecture Evolution: Field Experiences",
            "es": "Evolución en la arquitectura Cloud Native: Experiencias de Campo"
          },
          "slidesUrl": null
        },
        {
          "name": "Angel Ramirez",
          "affiliation": "Cuemby",
          "talk": {
            "en": "From Zero to a Bare-Metal Kubernetes Cluster",
            "es": "De Cero a Crear un Clúster de Kubernetes en Baremetal"
          },
          "slidesUrl": null
        },
        {
          "name": "Diego Rueda Pepinoza",
          "affiliation": "NTT Data Colombia – Leader Telecom",
          "talk": {
            "en": "Open-source solutions for university-level mobile network education",
            "es": "Soluciones open-source para la enseñanza universitaria de redes móviles"
          },
          "slidesUrl": null
        },
        {
          "name": "Mauricio Vargas",
          "affiliation": "SENNOVA – Centro de Electricidad, Electrónica y Telecomunicaciones",
          "talk": {
            "en": "Implementation of a 5G network testbed",
            "es": "Implementación de un testbed para redes 5G"
          },
          "slidesUrl": null
        }
      ]
    },
    {
      "id": "evt-2",
      "number": 2,
      "title": {
        "en": "Second Colombia OpenInfra User Group Hybrid Event",
        "es": "Segundo Evento Híbrido Colombia OpenInfra User Group"
      },
      "date": "2023-04-27",
      "venue": "Universidad del Quindío, Armenia",
      "attendees": 32,
      "upcoming": false,
      "description": {
        "en": "Second hybrid event of the group. Exploration of the latest advancements in LOKI open-source tools: Linux, OpenStack, Kubernetes and Infrastructure, showcasing developments from the Colombian community.",
        "es": "Segundo evento híbrido del grupo. Exploración de las últimas novedades en herramientas open-source LOKI: Linux, OpenStack, Kubernetes e Infraestructura, con ponentes de la comunidad colombiana."
      },
      "meetupUrl": "https://www.meetup.com/colombia-openinfra-user-group/events/289854934/",
      "imageUrl": "https://secure.meetupstatic.com/photos/event/6/c/9/f/highres_512427807.jpeg",
      "speakers": [
        {
          "name": "Juan Camilo Colorado",
          "affiliation": "Universidad del Quindío – GITUQ",
          "talk": {
            "en": "LTE-based 5G Terrestrial Broadcast project results (with IDTOLU)",
            "es": "Resultados del proyecto LTE-based 5G Terrestrial Broadcast (con IDTOLU)"
          },
          "slidesUrl": null
        },
        {
          "name": "Juan Pablo Gutierrez",
          "affiliation": "Universidad del Quindío – GITUQ",
          "talk": {
            "en": "LTE-based 5G Terrestrial Broadcast project results (with IDTOLU)",
            "es": "Resultados del proyecto LTE-based 5G Terrestrial Broadcast (con IDTOLU)"
          },
          "slidesUrl": null
        },
        {
          "name": "Alvaro Soto",
          "affiliation": null,
          "talk": {
            "en": "Cloud computing and data sovereignty",
            "es": "Computación en la nube y soberanía de datos"
          },
          "slidesUrl": null
        },
        {
          "name": "Kendall Nelson",
          "affiliation": "OpenInfra Foundation",
          "talk": {
            "en": "The 4 Opens methodology",
            "es": "La metodología de los 4 Opens"
          },
          "slidesUrl": null
        },
        {
          "name": "Juan Camilo Caviedez",
          "affiliation": null,
          "talk": {
            "en": "Experience deploying LOKI tools",
            "es": "Experiencia desplegando herramientas LOKI"
          },
          "slidesUrl": null
        },
        {
          "name": "Jhonny Athortua",
          "affiliation": null,
          "talk": {
            "en": "OpenStack deployment",
            "es": "Despliegue de OpenStack"
          },
          "slidesUrl": null
        },
        {
          "name": "Eritson Julio",
          "affiliation": "IDTOLU",
          "talk": {
            "en": "Cloud automation tools",
            "es": "Herramientas de automatización en la nube"
          },
          "slidesUrl": null
        },
        {
          "name": "Cesar Perez",
          "affiliation": "IDTOLU",
          "talk": {
            "en": "Cloud automation tools",
            "es": "Herramientas de automatización en la nube"
          },
          "slidesUrl": null
        }
      ]
    },
    {
      "id": "evt-1",
      "number": 1,
      "title": {
        "en": "First Colombia OpenInfra User Group Event",
        "es": "Primer Evento Colombia OpenInfra User Group"
      },
      "date": "2022-11-11",
      "venue": "Online",
      "attendees": 20,
      "upcoming": false,
      "description": {
        "en": "First Colombia OpenInfra User Group event. Private cloud-native deployment at ID:TOLU applied to next-generation telecommunications networks using LOKI (Linux, OpenStack, Kubernetes and Infrastructure).",
        "es": "Primer evento en Colombia del grupo de usuarios OpenInfra. Despliegue de la nube nativa privada en ID:TOLU aplicado a redes de telecomunicaciones de próxima generación usando LOKI (Linux, OpenStack, Kubernetes e Infraestructura)."
      },
      "meetupUrl": "https://www.meetup.com/colombia-openinfra-user-group/events/288637222/",
      "imageUrl": "https://secure.meetupstatic.com/photos/event/d/f/9/9/highres_508497241.jpeg",
      "speakers": [
        {
          "name": "Juan Pablo Noreña",
          "affiliation": null,
          "talk": {
            "en": "LXD & MAAS Microcloud: An Edge Alternative to OpenStack",
            "es": "Micronube de LXD y MAAS: Alternativa a OpenStack en el borde"
          },
          "slidesUrl": null
        },
        {
          "name": "Alvaro Soto",
          "affiliation": null,
          "talk": {
            "en": "Tailoring LOKI for Telcos",
            "es": "Tailoring LOKI for Telcos"
          },
          "slidesUrl": null
        },
        {
          "name": "Cesar Perez",
          "affiliation": "ID:TOLÚ",
          "talk": {
            "en": "OpenStack API integration for ID:TOLÚ testbed operations",
            "es": "Integración de las APIs de OpenStack para la operación del testbed de ID:TOLÚ"
          },
          "slidesUrl": null
        },
        {
          "name": "Eritson Julio",
          "affiliation": "ID:TOLÚ",
          "talk": {
            "en": "ID:TOLÚ cloud-native deployment with MAAS and OpenStack",
            "es": "Despliegue de la nube nativa de ID:TOLÚ usando MAAS y OpenStack"
          },
          "slidesUrl": null
        },
        {
          "name": "Juan Carlos Otero",
          "affiliation": "ID:TOLÚ",
          "talk": {
            "en": "ID:TOLÚ cloud-native deployment with MAAS and OpenStack",
            "es": "Despliegue de la nube nativa de ID:TOLÚ usando MAAS y OpenStack"
          },
          "slidesUrl": null
        }
      ]
    }
  ],
  "upcoming": [
    {
      "id": "evt-6",
      "number": 6,
      "title": {
        "en": "Sixth Event",
        "es": "Sexto Evento"
      },
      "date": "2026-09-15",
      "venue": "Universidad de los Andes",
      "attendees": null,
      "upcoming": true,
      "description": {
        "en": "",
        "es": ""
      },
      "meetupUrl": "https://www.meetup.com/colombia-openinfra-user-group/events/test2",
      "imageUrl": "assets/Cover Website - 6.svg",
      "speakers": []
    }
  ],
  "people": [
    {
      "id": 28,
      "role": "co-organizer",
      "name": "Santiago Chacón",
      "bio": {
        "phone": "+573219790207"
      },
      "company": null,
      "titleJob": null,
      "photoUrl": "https://media.licdn.com/dms/image/v2/D4E03AQHhyTIpquzIew/profile-displayphoto-shrink_400_400/B4EZTOGVrxHMAo-/0/1738624556253?e=1782950400&v=beta&t=ojGpkBG4Y5yrSK-vCHIDiqUEbBnoKbxsdhurHopKPS8",
      "linkedinUrl": "https://www.linkedin.com/in/santiago-c-145ab111a/",
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": null,
      "talks": [],
      "featured": false
    },
    {
      "id": 45,
      "role": "mentor",
      "name": "Carlos Arturo Quiroga",
      "bio": {
        "email": "carlosarturoq@gmail.com",
        "phone": "+573005525446"
      },
      "company": "Universidad de los Andes",
      "titleJob": null,
      "photoUrl": null,
      "linkedinUrl": "https://www.linkedin.com/in/carlosarturoq",
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": null,
      "talks": [],
      "featured": false
    },
    {
      "id": 46,
      "role": "mentor",
      "name": "Johan Gabriel Quiroga Rodriguez",
      "bio": {
        "email": "ggrodriguez1523@hotmail.com",
        "phone": "3102668705"
      },
      "company": "Geosystem/Trimble",
      "titleJob": null,
      "photoUrl": null,
      "linkedinUrl": "https://www.linkedin.com/in/johan-gabriel-quiroga-rodr%C3%ADguez/",
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": null,
      "talks": [],
      "featured": false
    },
    {
      "id": 37,
      "role": "organizer",
      "name": "Helena Spease",
      "bio": {
        "email": "helena@openinfra.org"
      },
      "company": "OpenInfra Foundation",
      "titleJob": "Community Programs Manager",
      "photoUrl": "https://media.licdn.com/dms/image/v2/D5603AQGi6othAh3Wgw/profile-displayphoto-scale_400_400/B56Z34zZ2eIQAg-/0/1777995720797?e=1782950400&v=beta&t=b3v8pAq8D0E-OF4m--xg2xdkFox825_D3umzCpz6vB8",
      "linkedinUrl": "https://www.linkedin.com/in/helena-spease/",
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": "https://openinfra.dev",
      "talks": [],
      "featured": false
    },
    {
      "id": 1,
      "role": "organizer",
      "name": "Luis Felipe Ariza Vesga",
      "bio": {
        "en": "",
        "es": ""
      },
      "company": "Beanters · Colombia OpenInfra User Group",
      "titleJob": "Founder & Community Organizer",
      "photoUrl": "/static/avatars/speakers/lfarizav.jpg",
      "linkedinUrl": "https://www.linkedin.com/in/luis-felipe-ariza-vesga/",
      "githubUrl": "https://github.com/lfarizav",
      "twitterUrl": null,
      "websiteUrl": null,
      "talks": [],
      "featured": true
    },
    {
      "id": 4,
      "role": "speaker",
      "name": "Alvaro Soto",
      "bio": {},
      "company": "Red Hat",
      "titleJob": "Senior Software Maintenance Engineer",
      "photoUrl": "/static/avatars/speakers/alsotoes.jpg",
      "linkedinUrl": null,
      "githubUrl": "https://github.com/alsotoes",
      "twitterUrl": null,
      "websiteUrl": "https://headup.ws",
      "talks": [],
      "featured": false
    },
    {
      "id": 16,
      "role": "speaker",
      "name": "Angel Ramirez",
      "bio": {},
      "company": "Cuemby",
      "titleJob": "CEO",
      "photoUrl": "/static/avatars/speakers/angel-ramirez.jpg",
      "linkedinUrl": "https://www.linkedin.com/in/ar4mirez",
      "githubUrl": "https://github.com/ar4mirez",
      "twitterUrl": null,
      "websiteUrl": "https://cuemby.com/",
      "talks": [],
      "featured": false
    },
    {
      "id": 5,
      "role": "speaker",
      "name": "Cesar Perez",
      "bio": {},
      "company": "IDTOLU",
      "titleJob": "Researcher",
      "photoUrl": null,
      "linkedinUrl": null,
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": "https://idtolu.com/",
      "talks": [],
      "featured": false
    },
    {
      "id": 24,
      "role": "speaker",
      "name": "Daniel Gerardo Escamilla Montoya",
      "bio": {},
      "company": "NTT DATA",
      "titleJob": "Lead Engineer",
      "photoUrl": "/static/avatars/speakers/daniel-escamilla.jpg",
      "linkedinUrl": null,
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": "https://www.nttdata.com/global/en/",
      "talks": [],
      "featured": false
    },
    {
      "id": 13,
      "role": "speaker",
      "name": "Daniel Jaramillo Ramirez",
      "bio": {},
      "company": "Pontificia Universidad Javeriana",
      "titleJob": "Researcher",
      "photoUrl": null,
      "linkedinUrl": null,
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": "https://www.javeriana.edu.co/",
      "talks": [],
      "featured": false
    },
    {
      "id": 20,
      "role": "speaker",
      "name": "Danilo Granados",
      "bio": {},
      "company": "Red Hat",
      "titleJob": "Technical Support Engineer — OpenShift",
      "photoUrl": "/static/avatars/speakers/danilo-granados.jpg",
      "linkedinUrl": null,
      "githubUrl": "https://github.com/danilogranadosg",
      "twitterUrl": null,
      "websiteUrl": null,
      "talks": [],
      "featured": false
    },
    {
      "id": 17,
      "role": "speaker",
      "name": "Diego Rueda Pepinoza",
      "bio": {},
      "company": "NTT Data Colombia",
      "titleJob": "Leader Telecom",
      "photoUrl": "/static/avatars/speakers/diego-rueda.jpg",
      "linkedinUrl": null,
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": "https://www.nttdata.com/global/en/",
      "talks": [],
      "featured": false
    },
    {
      "id": 6,
      "role": "speaker",
      "name": "Eritson Julio",
      "bio": {},
      "company": "IDTOLU",
      "titleJob": "Researcher",
      "photoUrl": "/static/avatars/speakers/eritson-julio.jpg",
      "linkedinUrl": "https://www.linkedin.com/in/eritson-julio-zarza-64640110b/",
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": "https://idtolu.com/",
      "talks": [],
      "featured": false
    },
    {
      "id": 25,
      "role": "speaker",
      "name": "Fabian Humberto Herrera Santana",
      "bio": {},
      "company": "Viceministerio de Conectividad",
      "titleJob": "Asesor",
      "photoUrl": "/static/avatars/speakers/fabian-herrera.jpg",
      "linkedinUrl": null,
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": null,
      "talks": [],
      "featured": false
    },
    {
      "id": 27,
      "role": "speaker",
      "name": "Gabriel Andrés Alzate Acuña",
      "bio": {},
      "company": "DatosCol",
      "titleJob": "CEO",
      "photoUrl": "/static/avatars/speakers/gabriel-alzate.jpg",
      "linkedinUrl": null,
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": null,
      "talks": [],
      "featured": false
    },
    {
      "id": 15,
      "role": "speaker",
      "name": "Iván Raul Camargo Chacón",
      "bio": {},
      "company": null,
      "titleJob": "Principal IT Architect",
      "photoUrl": "https://cache.sessionize.com/image/546a-400o400o2-B6GgUYxNkGkkrsC9o7NBdj.jpg",
      "linkedinUrl": null,
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": "https://sessionize.com/ivan-raul-camargo-chacon/",
      "talks": [],
      "featured": false
    },
    {
      "id": 14,
      "role": "speaker",
      "name": "Javier Andrés Marroquín Barreto",
      "bio": {},
      "company": "Pontificia Universidad Javeriana",
      "titleJob": "Researcher / Professor",
      "photoUrl": "/static/avatars/speakers/javier-marroquin.jpg",
      "linkedinUrl": null,
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": "https://www.javeriana.edu.co/",
      "talks": [],
      "featured": false
    },
    {
      "id": 26,
      "role": "speaker",
      "name": "Jhonnatan Gil Chaves",
      "bio": {},
      "company": "Globant",
      "titleJob": "DevOps/SRE Engineer",
      "photoUrl": "/static/avatars/speakers/jhonnatan-gil.jpg",
      "linkedinUrl": null,
      "githubUrl": "https://github.com/jhonnatangiladl",
      "twitterUrl": null,
      "websiteUrl": null,
      "talks": [],
      "featured": false
    },
    {
      "id": 12,
      "role": "speaker",
      "name": "Jhonny Atehortúa Ramos",
      "bio": {},
      "company": "Universidad del Quindío",
      "titleJob": "Researcher",
      "photoUrl": null,
      "linkedinUrl": null,
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": "https://www.uniquindio.edu.co/",
      "talks": [],
      "featured": false
    },
    {
      "id": 11,
      "role": "speaker",
      "name": "Juan Camilo Caviedez",
      "bio": {},
      "company": null,
      "titleJob": null,
      "photoUrl": "/static/avatars/speakers/juan-camilo-caviedez.jpg",
      "linkedinUrl": null,
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": null,
      "talks": [],
      "featured": false
    },
    {
      "id": 8,
      "role": "speaker",
      "name": "Juan Camilo Colorado",
      "bio": {},
      "company": "Universidad del Quindío",
      "titleJob": "Researcher — GITUQ",
      "photoUrl": "/static/avatars/speakers/juan-camilo-colorado.jpg",
      "linkedinUrl": null,
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": "https://www.uniquindio.edu.co/",
      "talks": [],
      "featured": false
    },
    {
      "id": 7,
      "role": "speaker",
      "name": "Juan Carlos Otero",
      "bio": {},
      "company": "IDTOLU",
      "titleJob": "Researcher",
      "photoUrl": "/static/avatars/speakers/juan-carlos-otero.jpg",
      "linkedinUrl": null,
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": "https://idtolu.com/",
      "talks": [],
      "featured": false
    },
    {
      "id": 9,
      "role": "speaker",
      "name": "Juan Pablo Gutierrez Yepes",
      "bio": {},
      "company": "Universidad del Quindío",
      "titleJob": "Researcher — GITUQ",
      "photoUrl": null,
      "linkedinUrl": "https://www.linkedin.com/in/juan-pablo-guti%C3%A9rrez-yepes-ab378927a/",
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": "https://www.uniquindio.edu.co/",
      "talks": [],
      "featured": false
    },
    {
      "id": 3,
      "role": "speaker",
      "name": "Juan Pablo Noreña Monsalve",
      "bio": {},
      "company": "Canonical",
      "titleJob": "Cloud Field Software Engineer",
      "photoUrl": null,
      "linkedinUrl": "https://www.linkedin.com/in/jpnorenam/",
      "githubUrl": "https://github.com/jpnorenam",
      "twitterUrl": null,
      "websiteUrl": null,
      "talks": [],
      "featured": false
    },
    {
      "id": 22,
      "role": "speaker",
      "name": "Juan Sebastian Clavijo",
      "bio": {},
      "company": "Pontificia Universidad Javeriana",
      "titleJob": "Student / Researcher",
      "photoUrl": null,
      "linkedinUrl": null,
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": "https://www.javeriana.edu.co/",
      "talks": [],
      "featured": false
    },
    {
      "id": 10,
      "role": "speaker",
      "name": "Kendall Nelson",
      "bio": {},
      "company": "OpenInfra Foundation",
      "titleJob": "Community Programs Manager",
      "photoUrl": "/static/avatars/speakers/kendall-nelson.jpg",
      "linkedinUrl": null,
      "githubUrl": "https://github.com/kendallnelson",
      "twitterUrl": null,
      "websiteUrl": "https://openinfra.dev/",
      "talks": [],
      "featured": false
    },
    {
      "id": 23,
      "role": "speaker",
      "name": "Mariela Curiel",
      "bio": {},
      "company": "Pontificia Universidad Javeriana",
      "titleJob": "Professor — Systems Engineering",
      "photoUrl": "/static/avatars/speakers/mariela-curiel.jpg",
      "linkedinUrl": null,
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": "https://www.javeriana.edu.co/",
      "talks": [],
      "featured": false
    },
    {
      "id": 18,
      "role": "speaker",
      "name": "Mauricio Alexander Vargas Rodríguez",
      "bio": {},
      "company": "SENNOVA / CEET",
      "titleJob": "Researcher",
      "photoUrl": null,
      "linkedinUrl": null,
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": null,
      "talks": [],
      "featured": false
    },
    {
      "id": 19,
      "role": "speaker",
      "name": "Nicolas Bayona",
      "bio": {},
      "company": "Endava",
      "titleJob": "DevOps Engineer — Kubestronaut",
      "photoUrl": "/static/avatars/speakers/nclsbayona.jpg",
      "linkedinUrl": null,
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": null,
      "talks": [],
      "featured": false
    },
    {
      "id": 21,
      "role": "speaker",
      "name": "Sergio Lopez",
      "bio": {},
      "company": "Pontificia Universidad Javeriana",
      "titleJob": "Student / Researcher",
      "photoUrl": "/static/avatars/speakers/sergio-lopez.jpg",
      "linkedinUrl": null,
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": "https://www.javeriana.edu.co/",
      "talks": [],
      "featured": false
    },
    {
      "id": 32,
      "role": "sponsor",
      "name": "Angel Ramirez",
      "bio": {
        "notes": "CEO Cuemby. Email estimado: ar4mirez@cuemby.com",
        "phone": "+1 786 503 4273",
        "sponsor_role": "Patrocinador"
      },
      "company": "Cuemby",
      "titleJob": "CEO & Founder",
      "photoUrl": "/static/avatars/speakers/angel-ramirez.jpg",
      "linkedinUrl": "https://www.linkedin.com/in/ar4mirez/",
      "githubUrl": "https://github.com/ar4mirez",
      "twitterUrl": null,
      "websiteUrl": "https://cuemby.com",
      "talks": [],
      "featured": false
    },
    {
      "id": 36,
      "role": "sponsor",
      "name": "Cristher Castro",
      "bio": {
        "notes": "Contacto Cuemby.",
        "phone": "+1 561 703 7129",
        "sponsor_role": "Patrocinador"
      },
      "company": "Cuemby",
      "titleJob": null,
      "photoUrl": "https://media.licdn.com/dms/image/v2/D4E03AQE95z0RATBiZA/profile-displayphoto-scale_400_400/B4EZneRgUuK0Ag-/0/1760370755535?e=1782950400&v=beta&t=JzftVAvPfUL3nH2eOoXxEyk6cWBK22jN1gHz-2dk34w",
      "linkedinUrl": "https://www.linkedin.com/in/cristhercastro/",
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": "https://cuemby.com",
      "talks": [],
      "featured": false
    },
    {
      "id": 34,
      "role": "sponsor",
      "name": "Daniel Jaramillo Ramírez",
      "bio": {
        "notes": "Contacto institucional Pontificia Universidad Javeriana.",
        "phone": "+57 304 618 0720",
        "sponsor_role": "Sede y Patrocinador Principal"
      },
      "company": "Pontificia Universidad Javeriana",
      "titleJob": "Researcher / Professor — Ingeniería de Sistemas",
      "photoUrl": "/static/avatars/speakers/daniel-jaramillo.jpg",
      "linkedinUrl": "https://www.linkedin.com/in/daniel-jaramillo-ram%C3%ADrez-8b89947/",
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": "https://www.javeriana.edu.co",
      "talks": [],
      "featured": false
    },
    {
      "id": 31,
      "role": "sponsor",
      "name": "Gabriela Maciel Tejeda",
      "bio": {
        "notes": "Contacto Whitestack. Oficina Bogotá: Cr 10 No. 96-25 Of 602.",
        "phone": "+52 55 1865 1834",
        "sponsor_role": "Patrocinador"
      },
      "company": "Whitestack",
      "titleJob": "Contacto Comercial",
      "photoUrl": "https://media.licdn.com/dms/image/v2/C4E03AQGf3gYag0Ning/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1550505134711?e=1782950400&v=beta&t=wsd4Z_iGfFnQAvQSrBWm5ye6O_5P8v-h0M4c-BmNTaY",
      "linkedinUrl": "https://www.linkedin.com/in/gabriela-maciel-tejeda-756ba758/",
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": "https://www.whitestack.com",
      "talks": [],
      "featured": false
    },
    {
      "id": 35,
      "role": "sponsor",
      "name": "Mariela Curiel",
      "bio": {
        "notes": "Contacto institucional Pontificia Universidad Javeriana.",
        "phone": "+57 318 307 0787",
        "sponsor_role": "Sede y Patrocinador Principal"
      },
      "company": "Pontificia Universidad Javeriana",
      "titleJob": "Profesora — Ingeniería de Sistemas",
      "photoUrl": "/static/avatars/speakers/mariela-curiel.jpg",
      "linkedinUrl": "https://www.linkedin.com/in/mariela-curiel-3a352b5/",
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": "https://www.javeriana.edu.co",
      "talks": [],
      "featured": false
    },
    {
      "id": 33,
      "role": "sponsor",
      "name": "Nicolas Castro",
      "bio": {
        "email": null,
        "notes": "Empresa de talent acquisition para ingenieros de IA. +15.000 desarrolladores remotos verificados. Contacto: https://www.theflock.com/en/build-your-software-development-team — agendar Discovery Call. Instagram: @theflockco. Sin contacto nombrado público — solicitar vía LinkedIn company page.",
        "phone": null,
        "sponsor_role": "Patrocinador"
      },
      "company": "The Flock Co",
      "titleJob": "Contacto Comercial",
      "photoUrl": "https://media.licdn.com/dms/image/v2/D4D03AQFOEC4Dqh-ENQ/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1709920063106?e=1782950400&v=beta&t=Y0SeICg7K239-l6saBHDMJaFuVLtCiGmjeRnt6pWBDc",
      "linkedinUrl": "https://www.linkedin.com/in/castro-nicolas/",
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": "https://www.theflock.com",
      "talks": [],
      "featured": false
    },
    {
      "id": 41,
      "role": "volunteer",
      "name": "Andrés Mauricio Rocha Ramos",
      "bio": {
        "email": "andrsrch@gmail.com",
        "phone": "3112667213"
      },
      "company": "EPAM Systems",
      "titleJob": null,
      "photoUrl": null,
      "linkedinUrl": "https://www.linkedin.com/in/andrsrch",
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": null,
      "talks": [],
      "featured": false
    },
    {
      "id": 49,
      "role": "volunteer",
      "name": "David Nieto",
      "bio": {
        "email": "davidlnieto66@gmail.com"
      },
      "company": null,
      "titleJob": null,
      "photoUrl": null,
      "linkedinUrl": null,
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": null,
      "talks": [],
      "featured": false
    },
    {
      "id": 44,
      "role": "volunteer",
      "name": "Francisco Moreno",
      "bio": {
        "email": "fmorenod@gmail.com",
        "phone": "3134978254"
      },
      "company": "Solvd",
      "titleJob": null,
      "photoUrl": null,
      "linkedinUrl": "https://www.linkedin.com/in/fmoreno",
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": null,
      "talks": [],
      "featured": false
    },
    {
      "id": 50,
      "role": "volunteer",
      "name": "Germán Velasco",
      "bio": {
        "email": "g.velasco@javeriana.edu.co"
      },
      "company": "Pontificia Universidad Javeriana",
      "titleJob": null,
      "photoUrl": null,
      "linkedinUrl": null,
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": null,
      "talks": [],
      "featured": false
    },
    {
      "id": 40,
      "role": "volunteer",
      "name": "Juan Diego Alvarado Gantiva",
      "bio": {
        "email": "juan.d.alvarado15@hotmail.com",
        "phone": "3214039029"
      },
      "company": "Infinite",
      "titleJob": null,
      "photoUrl": null,
      "linkedinUrl": "https://www.linkedin.com/in/juan-diego-alvarado-gantiva-7801a816a/",
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": null,
      "talks": [],
      "featured": false
    },
    {
      "id": 42,
      "role": "volunteer",
      "name": "Juan Pablo Arias Buitrago",
      "bio": {
        "email": "ariasj.u@javeriana.edu.co",
        "phone": "3154766820"
      },
      "company": "Pontificia Universidad Javeriana",
      "titleJob": null,
      "photoUrl": null,
      "linkedinUrl": "https://www.linkedin.com/in/juanp-arias-data-scientist/",
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": null,
      "talks": [],
      "featured": false
    },
    {
      "id": 47,
      "role": "volunteer",
      "name": "Salomón Alfredo Ávila",
      "bio": {
        "email": "salomon.avila2506@gmail.com"
      },
      "company": null,
      "titleJob": null,
      "photoUrl": null,
      "linkedinUrl": null,
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": null,
      "talks": [],
      "featured": false
    },
    {
      "id": 43,
      "role": "volunteer",
      "name": "Santiago Nicolás Cerón Dimate",
      "bio": {
        "email": "nicolasceron.d@gmail.com",
        "phone": "3163373216"
      },
      "company": "Universidad Javeriana",
      "titleJob": null,
      "photoUrl": null,
      "linkedinUrl": "https://www.linkedin.com/in/nicoceron/",
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": null,
      "talks": [],
      "featured": false
    },
    {
      "id": 48,
      "role": "volunteer",
      "name": "Saúl Andrés Menjura Ovalle",
      "bio": {
        "email": "andresovalle8@gmail.com"
      },
      "company": null,
      "titleJob": null,
      "photoUrl": null,
      "linkedinUrl": null,
      "githubUrl": null,
      "twitterUrl": null,
      "websiteUrl": null,
      "talks": [],
      "featured": false
    }
  ],
  "siteHealth": {
    "url": "https://beanters.com/colombia-openinfra-user-group/",
    "desktop": {
      "performance": 85,
      "accessibility": 96,
      "bestPractices": 96,
      "seo": 100,
      "fcp": "3.1 s",
      "lcp": "3.1 s",
      "tbt": "0 ms",
      "cls": "0.031"
    },
    "mobile": {
      "performance": 78,
      "accessibility": 96,
      "bestPractices": 96,
      "seo": 100,
      "fcp": "3.0 s",
      "lcp": "3.0 s",
      "tbt": "0 ms",
      "cls": "0.222"
    },
    "ux": {
      "passed": 22,
      "total": 22,
      "score": 100,
      "fails": []
    },
    "updated": "2026-06-15"
  }
};
