/* Colombia OpenInfra User Group — site content bridge.
 * This file is auto-regenerated by the Heritage /community/publish endpoint.
 * Edit via Heritage › Community control panel, not directly.
 */
window.SITE = {
  group: {
    name: "Colombia OpenInfra User Group",
    nameShort: "Colombia OpenInfra",
    description: {
      es: "Comunidad abierta para la colaboración y exploración de infraestructura abierta en Colombia. Reunimos a usuarios, desarrolladores y entusiastas de OpenStack, Kubernetes, cloud-native y tecnologías de infraestructura de código abierto.",
      en: "Open community for the collaboration and exploration of open infrastructure in Colombia. We bring together users, developers and enthusiasts of OpenStack, Kubernetes, cloud-native and open-source infrastructure technologies."
    },
    founded: "2022",
    members: 375,
    city: "Bogotá",
    country: "Colombia",
    countryCode: "CO",
    events: 6
  },
  socials: {
    meetup:    "https://www.meetup.com/colombia-openinfra-user-group/",
    youtube:   "https://www.youtube.com/@colombiaopeninfrausergroup",
    linkedin:  "https://www.linkedin.com/company/colombia-openinfra-user-group",
    instagram: "https://www.instagram.com/colombiaopeninfrausergroup/",
    github:    "https://github.com/lfarizav/colombia-openinfra-user-group"
  },
  registrationUrl: "https://www.meetup.com/colombia-openinfra-user-group/",
  chatUrl: "https://www.meetup.com/colombia-openinfra-user-group/",
  sponsors: [
    {
      name: "Pontificia Universidad Javeriana",
      url: "https://www.javeriana.edu.co",
      role: { es: "Sede y Patrocinador Principal", en: "Venue & Principal Sponsor" }
    },
    {
      name: "OpenInfra Foundation",
      url: "https://openinfra.dev",
      role: { es: "Fundación Organizadora", en: "Organizing Foundation" }
    }
  ],
  events: [
    {
      id: "evt-5",
      number: 5,
      title: {
        es: "5to Evento Colombia OpenInfra User Group",
        en: "5th Colombia OpenInfra User Group Event"
      },
      date: "2026-06-05",
      venue: "Pontificia Universidad Javeriana, Bogotá",
      attendees: null,
      upcoming: false,
      description: {
        es: "Quinto encuentro de la comunidad OpenInfra en Colombia. Sesiones sobre IA en Telco, Kubernetes, monitoreo con BPF, redes celulares privadas y desarrollo basado en especificaciones con IA.",
        en: "Fifth gathering of the OpenInfra community in Colombia. Sessions on AI in Telco, Kubernetes, BPF monitoring, private cellular networks, and specification-driven development with AI."
      },
      meetupUrl: "https://www.meetup.com/colombia-openinfra-user-group/",
      speakers: [
        {
          name: "Fabian Herrera",
          affiliation: "Universidad Javeriana",
          talk: {
            es: "IA y Telco",
            en: "AI and Telco"
          },
          slidesUrl: "presentations/IAyTelco-FabianHerrera.pdf"
        },
        {
          name: "Nicolás Bayona",
          affiliation: null,
          talk: {
            es: "De incidentes a decisiones informadas",
            en: "From incidents to informed decisions"
          },
          slidesUrl: "presentations/IncidentesADecisiones-NicolasBayona.pdf"
        },
        {
          name: "Luis Felipe Ariza Vesga",
          affiliation: "Beanters",
          talk: {
            es: "Despliegue de redes celulares privadas con lenguaje natural",
            en: "Deploy Private Cellular Networks Using Natural Language"
          },
          slidesUrl: "presentations/DeployPrivateCellularNetworksUsingNaturalLanguage-LuisAriza.pdf"
        },
        {
          name: "Gabriel Alzate",
          affiliation: null,
          talk: {
            es: "Desarrollo basado en especificaciones: reduciendo los costos de software a cero con IA y código abierto",
            en: "Specification-driven development: reducing software costs to zero with AI and open source"
          },
          slidesUrl: "presentations/DesarrolloBasadoEnEspecificaciones-GabrielAlzate.pdf"
        },
        {
          name: "Jhonnatan Gil",
          affiliation: null,
          talk: {
            es: "Monitoreo de alto rendimiento con BPF para servidores saturados",
            en: "High-performance BPF monitoring for saturated servers"
          },
          slidesUrl: "presentations/MonitoreoBPF-JhonnatanGil.pdf"
        },
        {
          name: "Mariela Curiel",
          affiliation: "Universidad Javeriana",
          talk: {
            es: "Semillas de Kubernetes en la Universidad Javeriana",
            en: "Kubernetes Seeds at Universidad Javeriana"
          },
          slidesUrl: "presentations/SemillasKubernetes-MarielaCuriel.pdf"
        }
      ]
    },
    {
      id: "evt-4",
      number: 4,
      title: {
        es: "KCD 2025 — Evento OpenInfra Colombia",
        en: "KCD 2025 — OpenInfra Colombia Event"
      },
      date: "2025-08-29",
      venue: "Bogotá, Colombia",
      attendees: 18,
      upcoming: false,
      description: {
        es: "Evento co-ubicado con Kubernetes Community Days 2025.",
        en: "Event co-located with Kubernetes Community Days 2025."
      },
      meetupUrl: "https://www.meetup.com/colombia-openinfra-user-group/",
      speakers: []
    },
    {
      id: "evt-3",
      number: 3,
      title: {
        es: "3er Evento Colombia OpenInfra User Group",
        en: "3rd Colombia OpenInfra User Group Event"
      },
      date: "2024-03-19",
      venue: "Bogotá, Colombia",
      attendees: 76,
      upcoming: false,
      description: {
        es: "Tercer encuentro de la comunidad con sesiones de infraestructura cloud-native.",
        en: "Third community gathering with cloud-native infrastructure sessions."
      },
      meetupUrl: "https://www.meetup.com/colombia-openinfra-user-group/",
      speakers: []
    }
  ],
  upcoming: [],
  people: [
    {
      id: "p-1", name: "Luis Felipe Ariza Vesga", role: "organizer",
      company: "Beanters", titleJob: "Founder & CTO",
      bio: {
        es: "Ingeniero PhD en telecomunicaciones, fundador de Beanters. Pionero en el despliegue de redes celulares privadas con IA y lenguaje natural. Organizador principal del Colombia OpenInfra User Group.",
        en: "PhD telecommunications engineer, founder of Beanters. Pioneer in private cellular network deployment using AI and natural language. Main organizer of the Colombia OpenInfra User Group."
      },
      linkedinUrl: "https://www.linkedin.com/in/lfarizav/",
      githubUrl: "https://github.com/lfarizav",
      twitterUrl: null, photoUrl: null, featured: true, active: true
    },
    {
      id: "p-2", name: "Fabian Herrera", role: "speaker",
      company: "Universidad Javeriana", titleJob: "AI & Telco Researcher",
      bio: {
        es: "Investigador especializado en la convergencia de inteligencia artificial y redes de telecomunicaciones móviles. Exploró cómo los modelos de lenguaje y los agentes transforman las redes 5G.",
        en: "Researcher specializing in the convergence of artificial intelligence and mobile telecommunications networks. Explored how language models and agents are transforming 5G networks."
      },
      linkedinUrl: null, githubUrl: null, twitterUrl: null, photoUrl: null,
      featured: true, active: true
    },
    {
      id: "p-3", name: "Nicolás Bayona", role: "speaker",
      company: null, titleJob: "Infrastructure Reliability Engineer",
      bio: {
        es: "Especialista en observabilidad y fiabilidad de infraestructura. Presentó cómo transformar datos de incidentes en decisiones informadas usando métricas y análisis de causa raíz.",
        en: "Specialist in infrastructure observability and reliability. Presented how to transform incident data into informed decisions using metrics and root cause analysis."
      },
      linkedinUrl: null, githubUrl: null, twitterUrl: null, photoUrl: null,
      featured: false, active: true
    },
    {
      id: "p-4", name: "Gabriel Alzate", role: "speaker",
      company: null, titleJob: "Software Engineer",
      bio: {
        es: "Ingeniero de software enfocado en desarrollo basado en especificaciones formales e IA. Exploró cómo reducir los costos de desarrollo a casi cero combinando IA y herramientas de código abierto.",
        en: "Software engineer focused on formal specification-driven development and AI. Explored how to reduce development costs to near zero combining AI with open-source tools."
      },
      linkedinUrl: null, githubUrl: null, twitterUrl: null, photoUrl: null,
      featured: false, active: true
    },
    {
      id: "p-5", name: "Jhonnatan Gil", role: "speaker",
      company: null, titleJob: "Kernel & Systems Engineer",
      bio: {
        es: "Experto en tecnologías BPF/eBPF para el kernel de Linux. Demostró técnicas de monitoreo de alto rendimiento para servidores con alta carga, sin impacto en producción.",
        en: "Expert in BPF/eBPF technologies for the Linux kernel. Demonstrated high-performance monitoring techniques for high-load servers with zero production impact."
      },
      linkedinUrl: null, githubUrl: null, twitterUrl: null, photoUrl: null,
      featured: false, active: true
    },
    {
      id: "p-6", name: "Mariela Curiel", role: "speaker",
      company: "Universidad Javeriana", titleJob: "Kubernetes Educator",
      bio: {
        es: "Educadora y promotora de Kubernetes en la Universidad Javeriana. Lidera las semillas de Kubernetes en la facultad, formando a la próxima generación de ingenieros cloud-native en Colombia.",
        en: "Kubernetes educator and promoter at Universidad Javeriana. Leads Kubernetes seeds in the faculty, training the next generation of cloud-native engineers in Colombia."
      },
      linkedinUrl: null, githubUrl: null, twitterUrl: null, photoUrl: null,
      featured: true, active: true
    }
  ]
};
